// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: msvqsc/msvqsc.proto

package msvqscpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Maximum VQ stages to use (fewer = more compression, lower fidelity).
	// 0 means use all available stages.
	MaxStages     int32 `protobuf:"varint,2,opt,name=max_stages,json=maxStages,proto3" json:"max_stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeRequest) Reset() {
	*x = EncodeRequest{}
	mi := &file_msvqsc_msvqsc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeRequest) ProtoMessage() {}

func (x *EncodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msvqsc_msvqsc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeRequest.ProtoReflect.Descriptor instead.
func (*EncodeRequest) Descriptor() ([]byte, []int) {
	return file_msvqsc_msvqsc_proto_rawDescGZIP(), []int{0}
}

func (x *EncodeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncodeRequest) GetMaxStages() int32 {
	if x != nil {
		return x.MaxStages
	}
	return 0
}

type EncodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Packed wire format: [1B header] [2B index per stage]
	Encoded []byte `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// Number of VQ stages actually used.
	StagesUsed int32 `protobuf:"varint,2,opt,name=stages_used,json=stagesUsed,proto3" json:"stages_used,omitempty"`
	// Estimated reconstruction fidelity (cosine similarity 0.0-1.0).
	EstimatedFidelity float32 `protobuf:"fixed32,3,opt,name=estimated_fidelity,json=estimatedFidelity,proto3" json:"estimated_fidelity,omitempty"`
	OriginalSize      int32   `protobuf:"varint,4,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	DurationMs        int32   `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EncodeResponse) Reset() {
	*x = EncodeResponse{}
	mi := &file_msvqsc_msvqsc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeResponse) ProtoMessage() {}

func (x *EncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msvqsc_msvqsc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeResponse.ProtoReflect.Descriptor instead.
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return file_msvqsc_msvqsc_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeResponse) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

func (x *EncodeResponse) GetStagesUsed() int32 {
	if x != nil {
		return x.StagesUsed
	}
	return 0
}

func (x *EncodeResponse) GetEstimatedFidelity() float32 {
	if x != nil {
		return x.EstimatedFidelity
	}
	return 0
}

func (x *EncodeResponse) GetOriginalSize() int32 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *EncodeResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type DecodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Packed wire format from EncodeResponse.encoded.
	Encoded       []byte `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRequest) Reset() {
	*x = DecodeRequest{}
	mi := &file_msvqsc_msvqsc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRequest) ProtoMessage() {}

func (x *DecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msvqsc_msvqsc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRequest.ProtoReflect.Descriptor instead.
func (*DecodeRequest) Descriptor() ([]byte, []int) {
	return file_msvqsc_msvqsc_proto_rawDescGZIP(), []int{2}
}

func (x *DecodeRequest) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

type DecodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reconstructed text (approximate).
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	StagesUsed    int32  `protobuf:"varint,2,opt,name=stages_used,json=stagesUsed,proto3" json:"stages_used,omitempty"`
	DurationMs    int32  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeResponse) Reset() {
	*x = DecodeResponse{}
	mi := &file_msvqsc_msvqsc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResponse) ProtoMessage() {}

func (x *DecodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msvqsc_msvqsc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResponse.ProtoReflect.Descriptor instead.
func (*DecodeResponse) Descriptor() ([]byte, []int) {
	return file_msvqsc_msvqsc_proto_rawDescGZIP(), []int{3}
}

func (x *DecodeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DecodeResponse) GetStagesUsed() int32 {
	if x != nil {
		return x.StagesUsed
	}
	return 0
}

func (x *DecodeResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_msvqsc_msvqsc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msvqsc_msvqsc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_msvqsc_msvqsc_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ready           bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	EncoderModel    string                 `protobuf:"bytes,2,opt,name=encoder_model,json=encoderModel,proto3" json:"encoder_model,omitempty"`
	CodebookStages  int32                  `protobuf:"varint,3,opt,name=codebook_stages,json=codebookStages,proto3" json:"codebook_stages,omitempty"`
	CodebookEntries int32                  `protobuf:"varint,4,opt,name=codebook_entries,json=codebookEntries,proto3" json:"codebook_entries,omitempty"`
	EmbeddingDim    int32                  `protobuf:"varint,5,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	CorpusSize      int32                  `protobuf:"varint,6,opt,name=corpus_size,json=corpusSize,proto3" json:"corpus_size,omitempty"`
	Device          string                 `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_msvqsc_msvqsc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msvqsc_msvqsc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_msvqsc_msvqsc_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetEncoderModel() string {
	if x != nil {
		return x.EncoderModel
	}
	return ""
}

func (x *HealthResponse) GetCodebookStages() int32 {
	if x != nil {
		return x.CodebookStages
	}
	return 0
}

func (x *HealthResponse) GetCodebookEntries() int32 {
	if x != nil {
		return x.CodebookEntries
	}
	return 0
}

func (x *HealthResponse) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

func (x *HealthResponse) GetCorpusSize() int32 {
	if x != nil {
		return x.CorpusSize
	}
	return 0
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

var File_msvqsc_msvqsc_proto protoreflect.FileDescriptor

const file_msvqsc_msvqsc_proto_rawDesc = "" +
	"\n" +
	"\x13msvqsc/msvqsc.proto\x12\x06msvqsc\"B\n" +
	"\rEncodeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"max_stages\x18\x02 \x01(\x05R\tmaxStages\"\xc0\x01\n" +
	"\x0eEncodeResponse\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\x12\x1f\n" +
	"\vstages_used\x18\x02 \x01(\x05R\n" +
	"stagesUsed\x12-\n" +
	"\x12estimated_fidelity\x18\x03 \x01(\x02R\x11estimatedFidelity\x12#\n" +
	"\roriginal_size\x18\x04 \x01(\x05R\foriginalSize\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\")\n" +
	"\rDecodeRequest\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\"f\n" +
	"\x0eDecodeResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vstages_used\x18\x02 \x01(\x05R\n" +
	"stagesUsed\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\"\x0f\n" +
	"\rHealthRequest\"\xfd\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12#\n" +
	"\rencoder_model\x18\x02 \x01(\tR\fencoderModel\x12'\n" +
	"\x0fcodebook_stages\x18\x03 \x01(\x05R\x0ecodebookStages\x12)\n" +
	"\x10codebook_entries\x18\x04 \x01(\x05R\x0fcodebookEntries\x12#\n" +
	"\rembedding_dim\x18\x05 \x01(\x05R\fembeddingDim\x12\x1f\n" +
	"\vcorpus_size\x18\x06 \x01(\x05R\n" +
	"corpusSize\x12\x16\n" +
	"\x06device\x18\a \x01(\tR\x06device2\xba\x01\n" +
	"\rMSVQSCService\x127\n" +
	"\x06Encode\x12\x15.msvqsc.EncodeRequest\x1a\x16.msvqsc.EncodeResponse\x127\n" +
	"\x06Decode\x12\x15.msvqsc.DecodeRequest\x1a\x16.msvqsc.DecodeResponse\x127\n" +
	"\x06Health\x12\x15.msvqsc.HealthRequest\x1a\x16.msvqsc.HealthResponseB$Z\"meshsat/internal/compress/msvqscpbb\x06proto3"

var (
	file_msvqsc_msvqsc_proto_rawDescOnce sync.Once
	file_msvqsc_msvqsc_proto_rawDescData []byte
)

func file_msvqsc_msvqsc_proto_rawDescGZIP() []byte {
	file_msvqsc_msvqsc_proto_rawDescOnce.Do(func() {
		file_msvqsc_msvqsc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msvqsc_msvqsc_proto_rawDesc), len(file_msvqsc_msvqsc_proto_rawDesc)))
	})
	return file_msvqsc_msvqsc_proto_rawDescData
}

var file_msvqsc_msvqsc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msvqsc_msvqsc_proto_goTypes = []any{
	(*EncodeRequest)(nil),  // 0: msvqsc.EncodeRequest
	(*EncodeResponse)(nil), // 1: msvqsc.EncodeResponse
	(*DecodeRequest)(nil),  // 2: msvqsc.DecodeRequest
	(*DecodeResponse)(nil), // 3: msvqsc.DecodeResponse
	(*HealthRequest)(nil),  // 4: msvqsc.HealthRequest
	(*HealthResponse)(nil), // 5: msvqsc.HealthResponse
}
var file_msvqsc_msvqsc_proto_depIdxs = []int32{
	0, // 0: msvqsc.MSVQSCService.Encode:input_type -> msvqsc.EncodeRequest
	2, // 1: msvqsc.MSVQSCService.Decode:input_type -> msvqsc.DecodeRequest
	4, // 2: msvqsc.MSVQSCService.Health:input_type -> msvqsc.HealthRequest
	1, // 3: msvqsc.MSVQSCService.Encode:output_type -> msvqsc.EncodeResponse
	3, // 4: msvqsc.MSVQSCService.Decode:output_type -> msvqsc.DecodeResponse
	5, // 5: msvqsc.MSVQSCService.Health:output_type -> msvqsc.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msvqsc_msvqsc_proto_init() }
func file_msvqsc_msvqsc_proto_init() {
	if File_msvqsc_msvqsc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msvqsc_msvqsc_proto_rawDesc), len(file_msvqsc_msvqsc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msvqsc_msvqsc_proto_goTypes,
		DependencyIndexes: file_msvqsc_msvqsc_proto_depIdxs,
		MessageInfos:      file_msvqsc_msvqsc_proto_msgTypes,
	}.Build()
	File_msvqsc_msvqsc_proto = out.File
	file_msvqsc_msvqsc_proto_goTypes = nil
	file_msvqsc_msvqsc_proto_depIdxs = nil
}
