// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: msvqsc/msvqsc.proto

package msvqscpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MSVQSCService_Encode_FullMethodName = "/msvqsc.MSVQSCService/Encode"
	MSVQSCService_Decode_FullMethodName = "/msvqsc.MSVQSCService/Decode"
	MSVQSCService_Health_FullMethodName = "/msvqsc.MSVQSCService/Health"
)

// MSVQSCServiceClient is the client API for MSVQSCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MSVQSCService provides rate-adaptive lossy semantic compression via
// multi-stage residual vector quantization (arXiv:2510.02646).
type MSVQSCServiceClient interface {
	// Encode compresses text into codebook indices (lossy).
	Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error)
	// Decode reconstructs approximate text from codebook indices.
	Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error)
	// Health returns sidecar readiness (model loaded, codebook status).
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type mSVQSCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMSVQSCServiceClient(cc grpc.ClientConnInterface) MSVQSCServiceClient {
	return &mSVQSCServiceClient{cc}
}

func (c *mSVQSCServiceClient) Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeResponse)
	err := c.cc.Invoke(ctx, MSVQSCService_Encode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mSVQSCServiceClient) Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeResponse)
	err := c.cc.Invoke(ctx, MSVQSCService_Decode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mSVQSCServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MSVQSCService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MSVQSCServiceServer is the server API for MSVQSCService service.
// All implementations must embed UnimplementedMSVQSCServiceServer
// for forward compatibility.
//
// MSVQSCService provides rate-adaptive lossy semantic compression via
// multi-stage residual vector quantization (arXiv:2510.02646).
type MSVQSCServiceServer interface {
	// Encode compresses text into codebook indices (lossy).
	Encode(context.Context, *EncodeRequest) (*EncodeResponse, error)
	// Decode reconstructs approximate text from codebook indices.
	Decode(context.Context, *DecodeRequest) (*DecodeResponse, error)
	// Health returns sidecar readiness (model loaded, codebook status).
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMSVQSCServiceServer()
}

// UnimplementedMSVQSCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMSVQSCServiceServer struct{}

func (UnimplementedMSVQSCServiceServer) Encode(context.Context, *EncodeRequest) (*EncodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encode not implemented")
}
func (UnimplementedMSVQSCServiceServer) Decode(context.Context, *DecodeRequest) (*DecodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decode not implemented")
}
func (UnimplementedMSVQSCServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMSVQSCServiceServer) mustEmbedUnimplementedMSVQSCServiceServer() {}
func (UnimplementedMSVQSCServiceServer) testEmbeddedByValue()                       {}

// UnsafeMSVQSCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MSVQSCServiceServer will
// result in compilation errors.
type UnsafeMSVQSCServiceServer interface {
	mustEmbedUnimplementedMSVQSCServiceServer()
}

func RegisterMSVQSCServiceServer(s grpc.ServiceRegistrar, srv MSVQSCServiceServer) {
	// If the following call panics, it indicates UnimplementedMSVQSCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MSVQSCService_ServiceDesc, srv)
}

func _MSVQSCService_Encode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSVQSCServiceServer).Encode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MSVQSCService_Encode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSVQSCServiceServer).Encode(ctx, req.(*EncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MSVQSCService_Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSVQSCServiceServer).Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MSVQSCService_Decode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSVQSCServiceServer).Decode(ctx, req.(*DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MSVQSCService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSVQSCServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MSVQSCService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSVQSCServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MSVQSCService_ServiceDesc is the grpc.ServiceDesc for MSVQSCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MSVQSCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msvqsc.MSVQSCService",
	HandlerType: (*MSVQSCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encode",
			Handler:    _MSVQSCService_Encode_Handler,
		},
		{
			MethodName: "Decode",
			Handler:    _MSVQSCService_Decode_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MSVQSCService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msvqsc/msvqsc.proto",
}
