# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msvqsc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'msvqsc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmsvqsc.proto\x12\x06msvqsc\"1\n\rEncodeRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x12\n\nmax_stages\x18\x02 \x01(\x05\"~\n\x0e\x45ncodeResponse\x12\x0f\n\x07\x65ncoded\x18\x01 \x01(\x0c\x12\x13\n\x0bstages_used\x18\x02 \x01(\x05\x12\x1a\n\x12\x65stimated_fidelity\x18\x03 \x01(\x02\x12\x15\n\roriginal_size\x18\x04 \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x05\" \n\rDecodeRequest\x12\x0f\n\x07\x65ncoded\x18\x01 \x01(\x0c\"H\n\x0e\x44\x65\x63odeResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bstages_used\x18\x02 \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x05\"\x0f\n\rHealthRequest\"\xa5\x01\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x15\n\rencoder_model\x18\x02 \x01(\t\x12\x17\n\x0f\x63odebook_stages\x18\x03 \x01(\x05\x12\x18\n\x10\x63odebook_entries\x18\x04 \x01(\x05\x12\x15\n\rembedding_dim\x18\x05 \x01(\x05\x12\x13\n\x0b\x63orpus_size\x18\x06 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x07 \x01(\t2\xba\x01\n\rMSVQSCService\x12\x37\n\x06\x45ncode\x12\x15.msvqsc.EncodeRequest\x1a\x16.msvqsc.EncodeResponse\x12\x37\n\x06\x44\x65\x63ode\x12\x15.msvqsc.DecodeRequest\x1a\x16.msvqsc.DecodeResponse\x12\x37\n\x06Health\x12\x15.msvqsc.HealthRequest\x1a\x16.msvqsc.HealthResponseB$Z\"meshsat/internal/compress/msvqscpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msvqsc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"meshsat/internal/compress/msvqscpb'
  _globals['_ENCODEREQUEST']._serialized_start=24
  _globals['_ENCODEREQUEST']._serialized_end=73
  _globals['_ENCODERESPONSE']._serialized_start=75
  _globals['_ENCODERESPONSE']._serialized_end=201
  _globals['_DECODEREQUEST']._serialized_start=203
  _globals['_DECODEREQUEST']._serialized_end=235
  _globals['_DECODERESPONSE']._serialized_start=237
  _globals['_DECODERESPONSE']._serialized_end=309
  _globals['_HEALTHREQUEST']._serialized_start=311
  _globals['_HEALTHREQUEST']._serialized_end=326
  _globals['_HEALTHRESPONSE']._serialized_start=329
  _globals['_HEALTHRESPONSE']._serialized_end=494
  _globals['_MSVQSCSERVICE']._serialized_start=497
  _globals['_MSVQSCSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
