# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import msvqsc_pb2 as msvqsc__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in msvqsc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MSVQSCServiceStub(object):
    """MSVQSCService provides rate-adaptive lossy semantic compression via
    multi-stage residual vector quantization (arXiv:2510.02646).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encode = channel.unary_unary(
                '/msvqsc.MSVQSCService/Encode',
                request_serializer=msvqsc__pb2.EncodeRequest.SerializeToString,
                response_deserializer=msvqsc__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.Decode = channel.unary_unary(
                '/msvqsc.MSVQSCService/Decode',
                request_serializer=msvqsc__pb2.DecodeRequest.SerializeToString,
                response_deserializer=msvqsc__pb2.DecodeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/msvqsc.MSVQSCService/Health',
                request_serializer=msvqsc__pb2.HealthRequest.SerializeToString,
                response_deserializer=msvqsc__pb2.HealthResponse.FromString,
                _registered_method=True)


class MSVQSCServiceServicer(object):
    """MSVQSCService provides rate-adaptive lossy semantic compression via
    multi-stage residual vector quantization (arXiv:2510.02646).
    """

    def Encode(self, request, context):
        """Encode compresses text into codebook indices (lossy).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decode(self, request, context):
        """Decode reconstructs approximate text from codebook indices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health returns sidecar readiness (model loaded, codebook status).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MSVQSCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encode': grpc.unary_unary_rpc_method_handler(
                    servicer.Encode,
                    request_deserializer=msvqsc__pb2.EncodeRequest.FromString,
                    response_serializer=msvqsc__pb2.EncodeResponse.SerializeToString,
            ),
            'Decode': grpc.unary_unary_rpc_method_handler(
                    servicer.Decode,
                    request_deserializer=msvqsc__pb2.DecodeRequest.FromString,
                    response_serializer=msvqsc__pb2.DecodeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=msvqsc__pb2.HealthRequest.FromString,
                    response_serializer=msvqsc__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msvqsc.MSVQSCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('msvqsc.MSVQSCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MSVQSCService(object):
    """MSVQSCService provides rate-adaptive lossy semantic compression via
    multi-stage residual vector quantization (arXiv:2510.02646).
    """

    @staticmethod
    def Encode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/msvqsc.MSVQSCService/Encode',
            msvqsc__pb2.EncodeRequest.SerializeToString,
            msvqsc__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/msvqsc.MSVQSCService/Decode',
            msvqsc__pb2.DecodeRequest.SerializeToString,
            msvqsc__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/msvqsc.MSVQSCService/Health',
            msvqsc__pb2.HealthRequest.SerializeToString,
            msvqsc__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
