#!/usr/bin/env bash
# install-kiosk.sh — provision the Pi into MeshSat kiosk mode.
# [MESHSAT-578 / 579 / 580]
#
# What this does:
#   1. apt-installs cage + chromium-browser + swayidle + curl + jq
#      (all stock Ubuntu 24.04 packages — no third-party repos).
#   2. Creates a `kiosk` user in the tty/video/input/render groups.
#   3. Drops an autologin override on getty@tty1 → boots straight
#      into that user on the console.
#   4. Installs the kiosk launcher (deploy/kiosk/meshsat-kiosk-session.sh)
#      into ~kiosk and wires it from .bash_profile so tty1 login
#      auto-launches `cage -- chromium --kiosk`.
#   5. Installs the Chromium managed-policy file
#      (deploy/kiosk/meshsat-kiosk.json) into
#      /etc/chromium/policies/managed/ — URL allowlist locked to
#      localhost, devtools + password manager + history disabled.
#
# Idempotent: safe to re-run. First-run takes ~90 s on a Pi 5
# (package install); subsequent runs <5 s.
#
# Usage:
#   sudo bash scripts/install-kiosk.sh              # default http://localhost:6050/?shell=kiosk
#   sudo BRIDGE_URL=http://foo:6050 bash scripts/install-kiosk.sh

set -euo pipefail

# ─── config ─────────────────────────────────────────────────────
BRIDGE_URL="${BRIDGE_URL:-http://localhost:6050/?shell=kiosk}"
KIOSK_USER="${KIOSK_USER:-kiosk}"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_DIR="$REPO_DIR/deploy/kiosk"

# ─── preflight ──────────────────────────────────────────────────
if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  echo "This script must run as root: sudo bash $0" >&2
  exit 1
fi
if [ ! -f "$DEPLOY_DIR/meshsat-kiosk-session.sh" ] || [ ! -f "$DEPLOY_DIR/meshsat-kiosk.json" ]; then
  echo "Deploy files missing — expected them under $DEPLOY_DIR" >&2
  exit 1
fi

echo "══ MeshSat kiosk provisioning ══"
echo "Bridge URL: $BRIDGE_URL"
echo "Kiosk user: $KIOSK_USER"
echo

# ─── 1. packages ────────────────────────────────────────────────
echo "[1/6] Installing packages…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y --no-install-recommends \
  cage chromium-browser swayidle curl jq

# ─── 2. kiosk user ──────────────────────────────────────────────
echo "[2/6] Creating kiosk user $KIOSK_USER (if missing)…"
if ! id "$KIOSK_USER" >/dev/null 2>&1; then
  useradd --create-home \
          --groups tty,video,input,render,audio \
          --shell /bin/bash \
          "$KIOSK_USER"
fi

# ─── 3. autologin on tty1 ───────────────────────────────────────
echo "[3/6] Enabling autologin for $KIOSK_USER on tty1…"
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat >/etc/systemd/system/getty@tty1.service.d/autologin.conf <<EOF
# Generated by meshsat scripts/install-kiosk.sh — edit the source
# script, not this file, or `sudo bash scripts/uninstall-kiosk.sh`
# to restore the stock getty.
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $KIOSK_USER --noclear %I \$TERM
EOF

# ─── 4. kiosk launcher + .bash_profile hook ─────────────────────
echo "[4/6] Installing kiosk launcher…"
install -D -m 0755 -o "$KIOSK_USER" -g "$KIOSK_USER" \
  "$DEPLOY_DIR/meshsat-kiosk-session.sh" \
  "/home/$KIOSK_USER/.local/bin/meshsat-kiosk-session.sh"

# Inject BRIDGE_URL into the installed copy so the session script is
# self-contained (no env-var dependency at login time).
sed -i "s|^BRIDGE_URL=.*|BRIDGE_URL=\"$BRIDGE_URL\"|" \
  "/home/$KIOSK_USER/.local/bin/meshsat-kiosk-session.sh"

# Hook into .bash_profile — idempotent (only append once).
mkdir -p "/home/$KIOSK_USER"
PROFILE="/home/$KIOSK_USER/.bash_profile"
touch "$PROFILE"
if ! grep -q 'meshsat-kiosk-session.sh' "$PROFILE"; then
  cat >>"$PROFILE" <<'EOF'

# meshsat kiosk — auto-launch on tty1 only. Source so .bash_profile
# env vars (PATH, etc) are in scope; the script exec's cage itself.
if [ -x "$HOME/.local/bin/meshsat-kiosk-session.sh" ]; then
  source "$HOME/.local/bin/meshsat-kiosk-session.sh"
fi
EOF
fi
chown "$KIOSK_USER:$KIOSK_USER" "$PROFILE"

# ─── 5. Chromium managed policy ─────────────────────────────────
echo "[5/6] Installing Chromium managed-policy file…"
install -D -m 0644 \
  "$DEPLOY_DIR/meshsat-kiosk.json" \
  /etc/chromium/policies/managed/meshsat-kiosk.json
# If the policy file carries the default URL, rewrite to whatever
# BRIDGE_URL the operator picked.
if [ "$BRIDGE_URL" != "http://localhost:6050/?shell=kiosk" ]; then
  # Use jq for a safe in-place rewrite.
  tmp=$(mktemp)
  jq --arg u "$BRIDGE_URL" \
    '.HomepageLocation=$u | .RestoreOnStartupURLs=[$u]' \
    /etc/chromium/policies/managed/meshsat-kiosk.json >"$tmp"
  mv "$tmp" /etc/chromium/policies/managed/meshsat-kiosk.json
fi

# ─── 6. reload systemd ──────────────────────────────────────────
echo "[6/6] Reloading systemd…"
systemctl daemon-reload

echo
echo "══ Kiosk provisioned ══"
echo "• Plug in the display (HDMI or Pi Touch Display 2) and reboot:"
echo "    sudo reboot"
echo "• After reboot the Pi boots straight into Chromium at:"
echo "    $BRIDGE_URL"
echo "• SSH + tty2/3/4 still give you a normal shell — only tty1"
echo "  is taken by the kiosk."
echo "• To back out:  sudo bash scripts/uninstall-kiosk.sh"
echo
