#!/usr/bin/env bash
# install-kiosk.sh — provision the Pi into MeshSat kiosk mode.
# [MESHSAT-578 / 579 / 580 / 577 DSI panel notes]
#
# What this does (all via stock Ubuntu 24.04 packages — zero third-
# party repos):
#   1. apt-installs labwc + chromium-browser + wlr-randr + swayidle
#      + curl + jq.
#   2. Creates a `kiosk` Linux user in the tty/video/input/render
#      groups.
#   3. Drops an autologin override on getty@tty1 → boots straight
#      into that user on the console.
#   4. Installs the kiosk launcher (meshsat-kiosk-session.sh) into
#      ~kiosk/.local/bin and wires it from .bash_profile so tty1
#      login auto-launches labwc.
#   5. Seeds labwc config: rc.xml (minimal compositor settings) +
#      autostart (wlr-randr rotate DSI-2 90°, then chromium kiosk
#      pointed at BRIDGE_URL).
#   6. Installs a udev rule that sets LIBINPUT_CALIBRATION_MATRIX
#      on the touchscreen so touch input rotates to match the
#      display output.
#   7. Installs the Chromium managed-policy file to lock the
#      kiosk to localhost (devtools + password manager + autofill
#      + history + printing all off).
#
# Idempotent — safe to re-run.
#
# Usage:
#   sudo bash scripts/install-kiosk.sh                      # defaults
#   sudo BRIDGE_URL=http://foo:6050 bash scripts/install-kiosk.sh

set -euo pipefail

# ─── config ─────────────────────────────────────────────────────
BRIDGE_URL="${BRIDGE_URL:-http://localhost:6050/?kiosk=1&shell=operator}"
KIOSK_USER="${KIOSK_USER:-kiosk}"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_DIR="$REPO_DIR/deploy/kiosk"

# ─── preflight ──────────────────────────────────────────────────
if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  echo "This script must run as root: sudo bash $0" >&2
  exit 1
fi
for f in meshsat-kiosk-session.sh meshsat-kiosk.json labwc-rc.xml labwc-autostart 99-touch-rotate.rules; do
  if [ ! -f "$DEPLOY_DIR/$f" ]; then
    echo "Deploy file missing: $DEPLOY_DIR/$f" >&2
    exit 1
  fi
done

echo "══ MeshSat kiosk provisioning ══"
echo "Bridge URL : $BRIDGE_URL"
echo "Kiosk user : $KIOSK_USER"
echo

# ─── 1. packages ────────────────────────────────────────────────
echo "[1/7] Installing packages…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y --no-install-recommends \
  labwc chromium-browser wlr-randr swayidle curl jq

# ─── 2. kiosk user ──────────────────────────────────────────────
echo "[2/7] Creating kiosk user $KIOSK_USER (if missing)…"
if ! id "$KIOSK_USER" >/dev/null 2>&1; then
  useradd --create-home \
          --groups tty,video,input,render,audio \
          --shell /bin/bash \
          "$KIOSK_USER"
fi

KIOSK_UID=$(id -u "$KIOSK_USER")

# ─── 3. autologin on tty1 ───────────────────────────────────────
echo "[3/7] Enabling autologin for $KIOSK_USER on tty1…"
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat >/etc/systemd/system/getty@tty1.service.d/autologin.conf <<EOF
# Generated by meshsat scripts/install-kiosk.sh — re-run the script
# to regenerate, or sudo bash scripts/uninstall-kiosk.sh to revert.
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $KIOSK_USER --noclear %I \$TERM
EOF

# ─── 4. kiosk launcher + .bash_profile hook ─────────────────────
echo "[4/7] Installing kiosk launcher…"
install -D -m 0755 -o "$KIOSK_USER" -g "$KIOSK_USER" \
  "$DEPLOY_DIR/meshsat-kiosk-session.sh" \
  "/home/$KIOSK_USER/.local/bin/meshsat-kiosk-session.sh"

# Hook into .bash_profile — idempotent (only append once).
PROFILE="/home/$KIOSK_USER/.bash_profile"
touch "$PROFILE"
if ! grep -q 'meshsat-kiosk-session.sh' "$PROFILE"; then
  cat >>"$PROFILE" <<'EOF'

# meshsat kiosk — auto-launch on tty1 only. Source so .bash_profile
# env vars (PATH, etc) are in scope; the script exec's labwc itself.
if [ -x "$HOME/.local/bin/meshsat-kiosk-session.sh" ]; then
  source "$HOME/.local/bin/meshsat-kiosk-session.sh"
fi
EOF
fi
chown "$KIOSK_USER:$KIOSK_USER" "$PROFILE"

# ─── 5. labwc config (rc.xml + autostart) ───────────────────────
echo "[5/7] Seeding labwc config…"
install -D -m 0644 -o "$KIOSK_USER" -g "$KIOSK_USER" \
  "$DEPLOY_DIR/labwc-rc.xml" \
  "/home/$KIOSK_USER/.config/labwc/rc.xml"

# Substitute BRIDGE_URL into autostart.  Escape `&` and `\` in the
# replacement so sed doesn't interpret `&` as the matched-pattern
# back-reference — the URL itself contains `&` (kiosk=1&shell=...)
# and that would otherwise get replaced with the literal
# __BRIDGE_URL__ marker.  Field lesson from parallax install 2026-04-20.
BRIDGE_URL_SED=$(printf '%s' "$BRIDGE_URL" | sed -e 's/[\\&|]/\\&/g')
tmp=$(mktemp)
sed "s|__BRIDGE_URL__|$BRIDGE_URL_SED|g" "$DEPLOY_DIR/labwc-autostart" >"$tmp"
install -D -m 0755 -o "$KIOSK_USER" -g "$KIOSK_USER" \
  "$tmp" "/home/$KIOSK_USER/.config/labwc/autostart"
rm -f "$tmp"

# ─── 6. udev rule for touch rotation ────────────────────────────
echo "[6/7] Installing touch-rotation udev rule…"
install -D -m 0644 \
  "$DEPLOY_DIR/99-touch-rotate.rules" \
  /etc/udev/rules.d/99-touch-rotate.rules
udevadm control --reload-rules
udevadm trigger --subsystem-match=input

# ─── 7. Chromium managed policy ─────────────────────────────────
echo "[7/7] Installing Chromium managed-policy file…"
install -D -m 0644 \
  "$DEPLOY_DIR/meshsat-kiosk.json" \
  /etc/chromium/policies/managed/meshsat-kiosk.json
if [ "$BRIDGE_URL" != "http://localhost:6050/?kiosk=1&shell=operator" ]; then
  tmp=$(mktemp)
  jq --arg u "$BRIDGE_URL" \
    '.HomepageLocation=$u | .RestoreOnStartupURLs=[$u]' \
    /etc/chromium/policies/managed/meshsat-kiosk.json >"$tmp"
  mv "$tmp" /etc/chromium/policies/managed/meshsat-kiosk.json
fi

echo "Installing blank cursor theme…"
bash "$DEPLOY_DIR/install-blank-cursor.sh"

# Let the kiosk user see the blank theme by default.
install -D -m 0644 -o "$KIOSK_USER" -g "$KIOSK_USER" /dev/stdin \
  "/home/$KIOSK_USER/.config/environment.d/50-cursor.conf" <<'EOF'
XCURSOR_THEME=blank
XCURSOR_SIZE=1
EOF

systemctl daemon-reload

echo
echo "══ Kiosk provisioned ══"
echo "• Cold-boot the Pi to apply cleanly (warm reboots can wedge"
echo "  the DSI bridge chip until a full power cycle):"
echo "    sudo poweroff   # then pull + restore power"
echo "• On boot the Pi auto-logs in as $KIOSK_USER and launches"
echo "  labwc → chromium at:"
echo "    $BRIDGE_URL"
echo "• tty2-6 (Ctrl+Alt+F2…F6) + SSH keep working."
echo "• To back out: sudo bash scripts/uninstall-kiosk.sh"
echo
