// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/compress/compress.proto

package compresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressRequest) Reset() {
	*x = CompressRequest{}
	mi := &file_proto_compress_compress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressRequest) ProtoMessage() {}

func (x *CompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compress_compress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressRequest.ProtoReflect.Descriptor instead.
func (*CompressRequest) Descriptor() ([]byte, []int) {
	return file_proto_compress_compress_proto_rawDescGZIP(), []int{0}
}

func (x *CompressRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CompressResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Compressed []byte                 `protobuf:"bytes,1,opt,name=compressed,proto3" json:"compressed,omitempty"`
	// Original size for ratio calculation.
	OriginalSize int32 `protobuf:"varint,2,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	// Compression duration in milliseconds.
	DurationMs    int32 `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressResponse) Reset() {
	*x = CompressResponse{}
	mi := &file_proto_compress_compress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressResponse) ProtoMessage() {}

func (x *CompressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compress_compress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressResponse.ProtoReflect.Descriptor instead.
func (*CompressResponse) Descriptor() ([]byte, []int) {
	return file_proto_compress_compress_proto_rawDescGZIP(), []int{1}
}

func (x *CompressResponse) GetCompressed() []byte {
	if x != nil {
		return x.Compressed
	}
	return nil
}

func (x *CompressResponse) GetOriginalSize() int32 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *CompressResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type DecompressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compressed    []byte                 `protobuf:"bytes,1,opt,name=compressed,proto3" json:"compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecompressRequest) Reset() {
	*x = DecompressRequest{}
	mi := &file_proto_compress_compress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompressRequest) ProtoMessage() {}

func (x *DecompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compress_compress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompressRequest.ProtoReflect.Descriptor instead.
func (*DecompressRequest) Descriptor() ([]byte, []int) {
	return file_proto_compress_compress_proto_rawDescGZIP(), []int{2}
}

func (x *DecompressRequest) GetCompressed() []byte {
	if x != nil {
		return x.Compressed
	}
	return nil
}

type DecompressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Decompression duration in milliseconds.
	DurationMs    int32 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecompressResponse) Reset() {
	*x = DecompressResponse{}
	mi := &file_proto_compress_compress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecompressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompressResponse) ProtoMessage() {}

func (x *DecompressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compress_compress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompressResponse.ProtoReflect.Descriptor instead.
func (*DecompressResponse) Descriptor() ([]byte, []int) {
	return file_proto_compress_compress_proto_rawDescGZIP(), []int{3}
}

func (x *DecompressResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DecompressResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_compress_compress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compress_compress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_compress_compress_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Ready     bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	ModelName string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Model size in bytes.
	ModelSizeBytes int64  `protobuf:"varint,3,opt,name=model_size_bytes,json=modelSizeBytes,proto3" json:"model_size_bytes,omitempty"`
	Device         string `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"` // "cpu" or "cuda"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_compress_compress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compress_compress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_compress_compress_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *HealthResponse) GetModelSizeBytes() int64 {
	if x != nil {
		return x.ModelSizeBytes
	}
	return 0
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

var File_proto_compress_compress_proto protoreflect.FileDescriptor

const file_proto_compress_compress_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/compress/compress.proto\x12\bcompress\"%\n" +
	"\x0fCompressRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"x\n" +
	"\x10CompressResponse\x12\x1e\n" +
	"\n" +
	"compressed\x18\x01 \x01(\fR\n" +
	"compressed\x12#\n" +
	"\roriginal_size\x18\x02 \x01(\x05R\foriginalSize\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\"3\n" +
	"\x11DecompressRequest\x12\x1e\n" +
	"\n" +
	"compressed\x18\x01 \x01(\fR\n" +
	"compressed\"I\n" +
	"\x12DecompressResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x05R\n" +
	"durationMs\"\x0f\n" +
	"\rHealthRequest\"\x87\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12(\n" +
	"\x10model_size_bytes\x18\x03 \x01(\x03R\x0emodelSizeBytes\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device2\xdd\x01\n" +
	"\x12CompressionService\x12A\n" +
	"\bCompress\x12\x19.compress.CompressRequest\x1a\x1a.compress.CompressResponse\x12G\n" +
	"\n" +
	"Decompress\x12\x1b.compress.DecompressRequest\x1a\x1c.compress.DecompressResponse\x12;\n" +
	"\x06Health\x12\x17.compress.HealthRequest\x1a\x18.compress.HealthResponseB&Z$meshsat/internal/compress/compresspbb\x06proto3"

var (
	file_proto_compress_compress_proto_rawDescOnce sync.Once
	file_proto_compress_compress_proto_rawDescData []byte
)

func file_proto_compress_compress_proto_rawDescGZIP() []byte {
	file_proto_compress_compress_proto_rawDescOnce.Do(func() {
		file_proto_compress_compress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compress_compress_proto_rawDesc), len(file_proto_compress_compress_proto_rawDesc)))
	})
	return file_proto_compress_compress_proto_rawDescData
}

var file_proto_compress_compress_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_compress_compress_proto_goTypes = []any{
	(*CompressRequest)(nil),    // 0: compress.CompressRequest
	(*CompressResponse)(nil),   // 1: compress.CompressResponse
	(*DecompressRequest)(nil),  // 2: compress.DecompressRequest
	(*DecompressResponse)(nil), // 3: compress.DecompressResponse
	(*HealthRequest)(nil),      // 4: compress.HealthRequest
	(*HealthResponse)(nil),     // 5: compress.HealthResponse
}
var file_proto_compress_compress_proto_depIdxs = []int32{
	0, // 0: compress.CompressionService.Compress:input_type -> compress.CompressRequest
	2, // 1: compress.CompressionService.Decompress:input_type -> compress.DecompressRequest
	4, // 2: compress.CompressionService.Health:input_type -> compress.HealthRequest
	1, // 3: compress.CompressionService.Compress:output_type -> compress.CompressResponse
	3, // 4: compress.CompressionService.Decompress:output_type -> compress.DecompressResponse
	5, // 5: compress.CompressionService.Health:output_type -> compress.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_compress_compress_proto_init() }
func file_proto_compress_compress_proto_init() {
	if File_proto_compress_compress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compress_compress_proto_rawDesc), len(file_proto_compress_compress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compress_compress_proto_goTypes,
		DependencyIndexes: file_proto_compress_compress_proto_depIdxs,
		MessageInfos:      file_proto_compress_compress_proto_msgTypes,
	}.Build()
	File_proto_compress_compress_proto = out.File
	file_proto_compress_compress_proto_goTypes = nil
	file_proto_compress_compress_proto_depIdxs = nil
}
