// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/compress/compress.proto

package compresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompressionService_Compress_FullMethodName   = "/compress.CompressionService/Compress"
	CompressionService_Decompress_FullMethodName = "/compress.CompressionService/Decompress"
	CompressionService_Health_FullMethodName     = "/compress.CompressionService/Health"
)

// CompressionServiceClient is the client API for CompressionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CompressionService provides LLM-based text compression via llama-zip.
type CompressionServiceClient interface {
	// Compress compresses text using LLM arithmetic coding.
	Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error)
	// Decompress decompresses data previously compressed by this service.
	Decompress(ctx context.Context, in *DecompressRequest, opts ...grpc.CallOption) (*DecompressResponse, error)
	// Health returns sidecar readiness (model loaded, GPU/CPU status).
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type compressionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompressionServiceClient(cc grpc.ClientConnInterface) CompressionServiceClient {
	return &compressionServiceClient{cc}
}

func (c *compressionServiceClient) Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompressResponse)
	err := c.cc.Invoke(ctx, CompressionService_Compress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compressionServiceClient) Decompress(ctx context.Context, in *DecompressRequest, opts ...grpc.CallOption) (*DecompressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecompressResponse)
	err := c.cc.Invoke(ctx, CompressionService_Decompress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compressionServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CompressionService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompressionServiceServer is the server API for CompressionService service.
// All implementations must embed UnimplementedCompressionServiceServer
// for forward compatibility.
//
// CompressionService provides LLM-based text compression via llama-zip.
type CompressionServiceServer interface {
	// Compress compresses text using LLM arithmetic coding.
	Compress(context.Context, *CompressRequest) (*CompressResponse, error)
	// Decompress decompresses data previously compressed by this service.
	Decompress(context.Context, *DecompressRequest) (*DecompressResponse, error)
	// Health returns sidecar readiness (model loaded, GPU/CPU status).
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCompressionServiceServer()
}

// UnimplementedCompressionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompressionServiceServer struct{}

func (UnimplementedCompressionServiceServer) Compress(context.Context, *CompressRequest) (*CompressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compress not implemented")
}
func (UnimplementedCompressionServiceServer) Decompress(context.Context, *DecompressRequest) (*DecompressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decompress not implemented")
}
func (UnimplementedCompressionServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCompressionServiceServer) mustEmbedUnimplementedCompressionServiceServer() {}
func (UnimplementedCompressionServiceServer) testEmbeddedByValue()                            {}

// UnsafeCompressionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompressionServiceServer will
// result in compilation errors.
type UnsafeCompressionServiceServer interface {
	mustEmbedUnimplementedCompressionServiceServer()
}

func RegisterCompressionServiceServer(s grpc.ServiceRegistrar, srv CompressionServiceServer) {
	// If the following call panics, it indicates UnimplementedCompressionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompressionService_ServiceDesc, srv)
}

func _CompressionService_Compress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressionServiceServer).Compress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompressionService_Compress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressionServiceServer).Compress(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompressionService_Decompress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressionServiceServer).Decompress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompressionService_Decompress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressionServiceServer).Decompress(ctx, req.(*DecompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompressionService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressionServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompressionService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressionServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompressionService_ServiceDesc is the grpc.ServiceDesc for CompressionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompressionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compress.CompressionService",
	HandlerType: (*CompressionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compress",
			Handler:    _CompressionService_Compress_Handler,
		},
		{
			MethodName: "Decompress",
			Handler:    _CompressionService_Decompress_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CompressionService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/compress/compress.proto",
}
